// Auto-generated by scripts/sync-hardcover.mjs — do not hand-edit.
// Regenerated daily by .github/workflows/hardcover-sync.yml from
// https://hardcover.app/@schie

export type HardcoverBook = {
  title: string;
  slug: string;
  author: string;
  imageUrl?: string;
  rating?: number;
};

export type FinishedHardcoverBook = HardcoverBook & {
  finishedDate?: string;
};

export const currentlyReading: HardcoverBook[] = [
  {
    title: "Kings of the Wyld",
    slug: "kings-of-the-wyld",
    author: "Nicholas Eames",
    imageUrl:
      "https://assets.hardcover.app/edition/30447628/23d6f2bd-115d-450f-a731-9fbcb59b04e8.jpg",
  },
  {
    title: "The Wild Robot Escapes",
    slug: "the-wild-robot-escapes",
    author: "Peter  Brown",
    imageUrl:
      "https://assets.hardcover.app/external_data/35422191/0fa8d7ceb502714596fbe26e4d6ae98d314e01fb.jpeg",
  },
  {
    title: "Arcanum Unbounded: The Cosmere Collection",
    slug: "arcanum-unbounded",
    author: "Brandon Sanderson",
    imageUrl:
      "https://assets.hardcover.app/edition/31276301/b5b1c6b758306caf9553430c4ccf576f29b9bd19.jpeg",
  },
];

export const recentlyFinished: FinishedHardcoverBook[] = [
  {
    title: "Warbreaker",
    slug: "warbreaker",
    author: "Brandon Sanderson",
    imageUrl:
      "https://assets.hardcover.app/edition/28188510/d2bfa4645e6a05879e663f2b72264dc150610210.jpeg",
    rating: 4.5,
    finishedDate: "2026-09-05",
  },
  {
    title: "A Short Stay in Hell",
    slug: "a-short-stay-in-hell",
    author: "Steven L. Peck",
    imageUrl:
      "https://assets.hardcover.app/edition/32076091/1fb38c39-58fb-4af1-8960-5b0ff1b9cbb4.jpg",
    rating: 4,
    finishedDate: "2026-08-30",
  },
  {
    title: "Mistborn: Secret History",
    slug: "mistborn-secret-history",
    author: "Brandon Sanderson",
    imageUrl:
      "https://assets.hardcover.app/editions/30399304/9d841b1c-40c4-4a52-96bc-221d34dbfe7e-71ISjS3nFsL._AC_UF1000,1000_QL80_.jpg",
    rating: 4.5,
    finishedDate: "2026-08-26",
  },
  {
    title: "The Bands of Mourning",
    slug: "the-bands-of-mourning",
    author: "Brandon Sanderson",
    imageUrl:
      "https://assets.hardcover.app/edition/20771821/40fd57bc-2a56-415b-8710-2d16878316b8.jpg",
    rating: 4.5,
    finishedDate: "2026-08-25",
  },
  {
    title: "One Dark Window",
    slug: "one-dark-window",
    author: "Rachel Gillig",
    imageUrl:
      "https://assets.hardcover.app/edition/31828939/9cf81169b82316d77a84c61e95c7edee0ca281b2.jpeg",
    rating: 2,
    finishedDate: "2026-08-01",
  },
  {
    title: "He Who Fights with Monsters 12",
    slug: "he-who-fights-with-monsters-12",
    author: "Travis Deverell, Shirtaloon",
    imageUrl:
      "https://assets.hardcover.app/editions/31894854/5417971590556350.jpg",
    finishedDate: "2026-08-01",
  },
];
