// Auto-generated by scripts/sync-hardcover.mjs — do not hand-edit.
// Regenerated daily by .github/workflows/hardcover-sync.yml from
// https://hardcover.app/@schie

export type HardcoverBook = {
  title: string;
  slug: string;
  author: string;
  imageUrl?: string;
  rating?: number;
};

export type FinishedHardcoverBook = HardcoverBook & {
  finishedDate?: string;
};

export const currentlyReading: HardcoverBook[] = [
  {
    title: "We Are Legion",
    slug: "we-are-legion",
    author: "Dennis E. Taylor",
    imageUrl:
      "https://assets.hardcover.app/edition/31651212/0f91da1379dc803e1a880cc526c86661808a6680.jpeg",
  },
  {
    title: "Empire of the Damned",
    slug: "empire-of-the-damned",
    author: "Jay Kristoff, Bon Orthwick",
    imageUrl:
      "https://assets.hardcover.app/edition/30883078/8478f02bc95cd56438f20ef95050d0cec01d8cb1.jpeg",
  },
  {
    title: "The Wild Robot Escapes",
    slug: "the-wild-robot-escapes",
    author: "Peter  Brown",
    imageUrl:
      "https://assets.hardcover.app/external_data/35422191/0fa8d7ceb502714596fbe26e4d6ae98d314e01fb.jpeg",
  },
];

export const recentlyFinished: FinishedHardcoverBook[] = [
  {
    title: "The Fires of December",
    slug: "the-fires-of-december",
    author: "Brandon Sanderson",
    imageUrl:
      "https://assets.hardcover.app/edition/32409522/5562a0b7-5a80-4b2e-b8a2-cc8f4780b904.png",
    rating: 3.5,
    finishedDate: "2026-09-26",
  },
  {
    title: "The Lost Metal",
    slug: "the-lost-metal",
    author: "Brandon Sanderson",
    imageUrl:
      "https://assets.hardcover.app/external_data/60987563/93e411dc55a6e9763635437407af2309d749fc4a.jpeg",
    rating: 4.5,
    finishedDate: "2026-09-20",
  },
  {
    title: "Empire of the Vampire",
    slug: "empire-of-the-vampire",
    author: "Bon Orthwick, Jay Kristoff",
    imageUrl:
      "https://assets.hardcover.app/editions/30548430/7973802927976714.jpg",
    rating: 4.5,
    finishedDate: "2026-09-16",
  },
  {
    title: "Kings of the Wyld",
    slug: "kings-of-the-wyld",
    author: "Nicholas Eames",
    imageUrl:
      "https://assets.hardcover.app/edition/30447628/23d6f2bd-115d-450f-a731-9fbcb59b04e8.jpg",
    rating: 3.5,
    finishedDate: "2026-09-09",
  },
  {
    title: "Warbreaker",
    slug: "warbreaker",
    author: "Brandon Sanderson",
    imageUrl:
      "https://assets.hardcover.app/edition/28188510/d2bfa4645e6a05879e663f2b72264dc150610210.jpeg",
    rating: 4.5,
    finishedDate: "2026-09-05",
  },
  {
    title: "A Short Stay in Hell",
    slug: "a-short-stay-in-hell",
    author: "Steven L. Peck",
    imageUrl:
      "https://assets.hardcover.app/edition/32076091/1fb38c39-58fb-4af1-8960-5b0ff1b9cbb4.jpg",
    rating: 4,
    finishedDate: "2026-08-30",
  },
];
